Added Docstring to get_user_method in canvas.py ,Added some text in…
ucfopen/canvasapi pull request #422
Opened 2020-10-01 18:49 UTC by Xx-Ashutosh-xX

… current-user-ref.rst explaining the inheritance of current_user class from user class

# Proposed Changes

*
*

Fixes # .

2020-10-02 09:38 UTC, Thetwam requested changes
Thanks for the PR, @Xx-Ashutosh-xX! We appreciate the help 😁 

Just a few suggested tweaks below:

2020-10-02 09:38 UTC, Thetwam commented on canvasapi/canvas.py
> +        :type user: :class:`cavasapi.user.User` or int
`:param:` and `:type:` are used to document the arguments of the function. In the case of `get_current_user`, there are no arguments (besides `self`, which needs no introduction), so these lines aren't necessary. Please remove them.

2020-10-02 09:38 UTC, Thetwam commented on docs/current-user-ref.rst
> +See : https://canvas.instructure.com/doc/api/users.html for details
In the issue, by "provide a link to the `User` class reference page", I meant in the CanvasAPI documentation (as generated from `user-ref.rst`)

You should be able to do that with a link something like this:

```rst
`Documentation for the User class <user-ref.html>`_
```

2020-10-02 09:38 UTC, Thetwam commented on docs/current-user-ref.rst
> +See : https://canvas.instructure.com/doc/api/users.html for details
Please move this section above the autoclass call

2020-10-02 14:48 UTC, Xx-Ashutosh-xX reviewed
* I have removed the :params: and :type: from canvas.py
* Added the URL of User class liked you Suggested

2020-10-05 19:06 UTC, Thetwam approved these changes

2020-10-05 19:06 UTC, merged

2020-10-05 19:24 UTC, Thetwam commented
Great work, @Xx-Ashutosh-xX, thanks! 👍