Fixes issue (#371) - Adds endpoint for file quota information
ucfopen/canvasapi pull request #458
Opened 2021-01-11 21:32 UTC by deundrewilliams

2021-01-12 18:53 UTC, Thetwam requested changes
Looks great! Just need to run `black canvasapi tests` and fix a docstring and it's good to go.

2021-01-12 18:53 UTC, Thetwam commented on canvasapi/user.py
> +        :calls: `GET /api/v1/groups/:group_id/files/quota \
Should be user

```suggestion
        :calls: `GET /api/v1/users/:user_id/files/quota \
```

2021-01-13 19:37 UTC, Thetwam requested changes
We like to keep the main files organized by alphabetizing methods. `get_file_quota` should come before `get_files`. You can see where the errors are by running `python scripts/alphabetic.py`.

If you want to run all linters, tests, etc. at once locally, you can also run `scripts/run_tests.sh`.

_(**Note**: this is not a common - or even recommended - practice elsewhere, we're just doing it in CanvasAPI to keep massive files like `course.py` manageable)_

2021-01-19 17:26 UTC, jessemcbride commented on canvasapi/course.py
> +        """
A tiny nitpick, but [docstrings shouldn't have a blank line between them and the function signature](https://www.python.org/dev/peps/pep-0257/#one-line-docstrings). It looks like it won't interfere with Python's ability to parse it as a docstring, but it's probably worth updating each function to eliminate the blank line for consistency's sake.

2021-01-26 19:48 UTC, Thetwam approved these changes

2021-01-26 19:54 UTC, merged